# Common settings
proj_name: enf_torch_airfrans_out
seed: 42
logging:
    log_dir: './experiments/training/'
    save_predictions: true

dataset:
  name: 'airfrans'  # or 'rae_transonic'
  root_path: '/scratch/dmsm/gi.catalani/Airfrans/Dataset/'  # adjust path as needed
  task: 'full'  # for airfrans dataset
  target_field: 'Pressure'
  test_latents_path: /home/dmsm/gi.catalani/Projects/enf-torch/enf-torch-main/experiments/training/2025-05-31_17-41-48/modulations/val_modulations.pt
  train_latents_path: /home/dmsm/gi.catalani/Projects/enf-torch/enf-torch-main/experiments/training/2025-05-31_17-41-48/modulations/train_modulations.pt
  num_points: null  # optional subsampling

model:
  num_hidden: 256
  num_heads: 2
  num_layers: 2
  num_out: 1
  latent_dim: 10
  gaussian_window: 0.2
  num_latents: 9
  in_dim: 3
  spatial_dim: 2
  embedding_type: 'rff'
  emb_freq_q: 2
  emb_freq_v: 2
  condition_value_transform: true
  freeze_lat_pos: true
  use_enhanced_stem: true
  use_lightweight_self_attn: true
  latent_bbox: [[-0.5,0.25],[-0.25,0.25]]  # Set this to the bounding box of your dataset
  checkpoint_directory: null

optimizer:
  learning_rate_enf: 0.0001
  learning_rate_codes: 0.0

train: 
    device: 'cuda'

optim: 
  batch_size: 1
  epochs: 3000
  inner_steps: 
  num_points: 2000
  lr_enf: 0.0001
  lr_latents: 